
const getExtension = (contentType) => {
	switch (contentType) {
	case 'text/html':
		return 'html'
	case 'text/css':
		return 'css'
	case 'text/xml':
		return 'xml'
	case 'image/gif':
		return 'gif'
	case 'image/jpeg':
		return 'jpg'
	case 'application/x-javascript':
		return 'js'
	case 'application/atom+xml':
		return 'atom'
	case 'application/rss+xml':
		return 'rss'
	case 'text/mathml':
		return 'mml'
	case 'text/plain':
		return 'txt'
	case 'text/vnd.sun.j2me.app-descriptor':
		return 'jad'
	case 'text/vnd.wap.wml':
		return 'wml'
	case 'text/x-component':
		return 'htc'
	case 'image/png':
		return ' png'
	case 'image/tiff':
		return 'tiff'
	case 'image/vnd.wap.wbmp':
		return 'wbmp'
	case 'image/x-icon':
		return 'ico'
	case 'image/x-jng':
		return 'jng'
	case 'image/x-ms-bmp':
		return 'bmp'
	case 'image/svg+xml':
		return 'svg'
	case 'image/webp':
		return 'webp'
	case 'application/java-archive':
		return 'jar'
	case 'application/msword':
		return 'doc'
	case 'application/pdf':
		return 'pdf'
	case 'application/postscript':
		return 'ps'
	case 'application/vnd.ms-excel':
		return 'xls'
	case 'application/vnd.ms-powerpoint':
		return 'ppt'
	case 'application/vnd.wap.wmlc':
		return 'wmlc'
	case 'application/x-7z-compressed':
		return '7z'
	case 'application/x-rar-compressed':
		return 'rar'
	case 'application/x-shockwave-flash':
		return 'swf'
	case 'application/x-xpinstall':
		return 'xpi'
	case 'application/xhtml+xml':
		return 'xhtml'
	case 'application/zip':
		return 'zip'
	case 'audio/mpeg':
		return 'mp3'
	case 'video/3gpp':
		return '3gp'
	case 'video/mpeg':
		return 'mpg'
	case 'video/quicktime':
		return 'mov'
	case 'video/x-flv':
		return 'flv'
	case 'video/x-mng':
		return 'mng'
	case 'video/x-ms-wmv':
		return 'wmv'
	case 'video/x-msvideo':
		return 'avi'
	case 'video/mp4':
		return 'mp4'
	}
}

module.exports = getExtension